# Generated by Django 5.2.1 on 2025-10-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('devops', 'DevOps'), ('data', 'Data'), ('tools', 'Tools/Other')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=3)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('pinned', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
