# Generated by Django 5.2.1 on 2025-11-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_technology_project_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
